### ISSUE TITLE
Typing while console is open interacts with the world

### ISSUE THREAD

**Issue by pipe01** [pipe01/PiTUNG#4]
For example, if you open the console and press T while looking at a component, the component will be deleted.

**Comment by Stenodyon** [comment]
Oh yeah I forgot to set ```UIManager.SomeOtherMenuIsOpen``` to true when opening the console. Also, related, when closing the pause menu when the console is open, the mouse is locked again

**Comment by pipe01** [comment]
Oh well then it's not as big of a problem as I thought, although the pause menu one might be tricky.
